--- @meta

--- @class AccessibleState: AccessibleBundle
--- @field public class any
--- @field public ACTIVE AccessibleState
--- @field public ARMED AccessibleState
--- @field public BUSY AccessibleState
--- @field public CHECKED AccessibleState
--- @field public COLLAPSED AccessibleState
--- @field public EDITABLE AccessibleState
--- @field public ENABLED AccessibleState
--- @field public EXPANDABLE AccessibleState
--- @field public EXPANDED AccessibleState
--- @field public FOCUSABLE AccessibleState
--- @field public FOCUSED AccessibleState
--- @field public HORIZONTAL AccessibleState
--- @field public ICONIFIED AccessibleState
--- @field public INDETERMINATE AccessibleState
--- @field public MANAGES_DESCENDANTS AccessibleState
--- @field public MODAL AccessibleState
--- @field public MULTI_LINE AccessibleState
--- @field public MULTISELECTABLE AccessibleState
--- @field public OPAQUE AccessibleState
--- @field public PRESSED AccessibleState
--- @field public RESIZABLE AccessibleState
--- @field public SELECTABLE AccessibleState
--- @field public SELECTED AccessibleState
--- @field public SHOWING AccessibleState
--- @field public SINGLE_LINE AccessibleState
--- @field public TRANSIENT AccessibleState
--- @field public TRUNCATED AccessibleState
--- @field public VERTICAL AccessibleState
--- @field public VISIBLE AccessibleState
AccessibleState = {};

